version: '3.8'

services:
  selenium-tests:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./target/reports:/app/target/reports
    environment:
      - LANGUAGE=java
    shm_size: '2gb'